__title__ = 'deploy_message'
__version__ = '0.1.0'
__url__ = 'https://github.com/UIUCLibrary/sccm_deploy_message_generator'
__author__ = 'University of Illinois at Urbana Champaign'
__author_email__ = 'hborcher@illinois.edu'
__description__ = 'Generates the message required for deployment'
maintainer = "Henry Borchers"
maintainer_email = "hborcher@illinois.edu"
download_url = "https://github.com/UIUCLibrary/sccm_deploy_message_generator"
license_ = "University of Illinois/NCSA Open Source License"
