language: python
python:
  - "3.6"
install:
  - "./.travis/install.sh"
script:
  - "./.travis/run.sh"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
