language: python
python:
- '3.6'
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  provider: releases
  overwrite: true
  api_key:
  file_glob: true
    secure: "$GITHUB_TOKEN"
  file: dist/*.tar.gz
  on:
    repo: UIUCLibrary/sccm_deploy_message_generator
